In [1]:
import requests
import pandas as pd
import numpy as np

### 1. Download FII's with requests

In [2]:
url = 'https://www.fundsexplorer.com.br/ranking'
headers = {
    'User-Agent': 
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36'
        ' (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
}

In [3]:
response = requests.get(url, headers=headers)

In [4]:
if response.status_code == 200:
    df_fiis = pd.read_html(response.content, encoding='utf-8')[0]

In [5]:
df_fiis

,Código do fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,DY (3M) Média,...,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira,Quantidade Ativos
0,FIVN11,Shoppings,"R$ 3,32",826.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 65.352.435,22","R$ 6,94",48.0,NaN,NaN,NaN,NaN,"56,00%",NaN,1
1,BZLI11,Títulos e Val. Mob.,"R$ 17,01",2.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 433.127.158,26","R$ 10,49",162.0,NaN,NaN,NaN,NaN,NaN,NaN,0
2,XTED11,Lajes Corporativas,"R$ 8,82",2223.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 27.688.895,17","R$ 13,26",67.0,NaN,NaN,NaN,NaN,"0,00%","100,00%",1
3,ALMI11,Lajes Corporativas,"R$ 885,00",32.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 250.446.109,75","R$ 2.252,68",39.0,NaN,NaN,NaN,NaN,"64,05%",NaN,1
4,PABY11,Híbrido,"R$ 21,68",380.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ -12.026.292,32","R$ -15,86",-137.0,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,BPML11,Shoppings,"R$ 62,48",94.0,"R$ 0,30","0,48%","1,37%","2,32%","0,00%","0,46%",...,"R$ 531.797.948,23","R$ 123,53",51.0,NaN,NaN,NaN,NaN,"5,80%",NaN,7
376,XPML11,Shoppings,"R$ 94,24",46428.0,"R$ 0,77","0,82%","2,29%","4,41%","8,71%","0,76%",...,"R$ 2.058.454.896,67","R$ 101,30",93.0,NaN,NaN,NaN,NaN,"3,90%",NaN,16
377,FCFL11,Outros,"R$ 111,00",4224.0,"R$ 0,76","0,69%","1,97%","4,20%","8,51%","0,66%",...,"R$ 364.091.433,44","R$ 104,80",106.0,NaN,NaN,NaN,NaN,"0,00%",NaN,1
378,XPIN11,Outros,"R$ 70,92",6374.0,"R$ 0,65","0,92%","2,51%","4,97%","9,41%","0,84%",...,"R$ 742.296.242,19","R$ 103,81",68.0,NaN,NaN,NaN,NaN,"17,30%","12,00%",5
379,EQIR11,Títulos e Val. Mob.,"R$ 9,69",3784.0,"R$ 0,11","1,14%","3,43%","17,04%","0,00%","1,14%",...,"R$ 49.267.646,34","R$ 9,80",99.0,NaN,NaN,NaN,NaN,NaN,NaN,0

In [6]:
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Código do fundo           380 non-null    object
 1   Setor                     364 non-null    object
 2   Preço Atual               379 non-null    object
 3   Liquidez Diária           379 non-null    float64
 4   Dividendo                 380 non-null    object
 5   Dividend Yield            374 non-null    object
 6   DY (3M) Acumulado         374 non-null    object
 7   DY (6M) Acumulado         374 non-null    object
 8   DY (12M) Acumulado        374 non-null    object
 9   DY (3M) Média             374 non-null    object
 10  DY (6M) Média             374 non-null    object
 11  DY (12M) Média            374 non-null    object
 12  DY Ano                    336 non-null    object
 13  Variação Preço            374 non-null    object
 14  Rentab. Período           374 non-null    object
 15  Rentab. Acumulada         374 non-null    object
 16  Patrimônio Líq.           371 non-null    object
 17  VPA                       371 non-null    object
 18  P/VPA                     370 non-null    float64
 19  DY Patrimonial            282 non-null    object
 20  Variação Patrimonial      282 non-null    object
 21  Rentab. Patr. no Período  282 non-null    object
 22  Rentab. Patr. Acumulada   282 non-null    object
 23  Vacância Física           130 non-null    object
 24  Vacância Financeira       30 non-null     object
 25  Quantidade Ativos         380 non-null    int64
dtypes: float64(2), int64(1), object(23)
memory usage: 77.3+ KB

In [7]:
df_fiis.describe(include='all')

,Código do fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,DY (3M) Média,...,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira,Quantidade Ativos
count,380,364,379,3.790000e+02,380,374,374,374,374,374,...,371,371,370.000000,282,282,282,282,130,30,380.000000
unique,297,11,344,NaN,120,104,182,213,220,106,...,288,282,NaN,114,168,174,225,73,18,NaN
top,ERCR11,Títulos e Val. Mob.,"R$ 10,03",NaN,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%",...,"R$ 160.268.446,24","R$ 67.453,05",NaN,"0,57%","0,00%","0,66%","16,02%","0,00%","0,00%",NaN
freq,16,99,4,NaN,21,46,52,61,95,52,...,16,16,NaN,12,25,11,9,42,13,NaN
mean,NaN,NaN,NaN,2.694623e+04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,73.886486,NaN,NaN,NaN,NaN,NaN,NaN,2.328947
std,NaN,NaN,NaN,1.715904e+05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,57.016929,NaN,NaN,NaN,NaN,NaN,NaN,6.781918
min,NaN,NaN,NaN,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-137.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,4.270000e+02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,2.624000e+03,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,82.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,1.225400e+04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,93.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,NaN,3.180000e+06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,949.000000,NaN,NaN,NaN,NaN,NaN,NaN,72.000000

### 2. Cleaning and formatting

In [8]:
df_fiis['Setor'].unique()

array(['Shoppings', 'Títulos e Val. Mob.', 'Lajes Corporativas',
       'Híbrido', 'Residencial', 'Outros', 'Logística', 'Hospital', nan,
       'Títulos e Valores Mobiliários', 'Hotel', 'Renda'], dtype=object)

In [9]:
df_fiis = df_fiis.replace('Títulos e Valores Mobiliários', 'Títulos e Val. Mob.', regex=False)
df_fiis['Setor'].unique()

array(['Shoppings', 'Títulos e Val. Mob.', 'Lajes Corporativas',
       'Híbrido', 'Residencial', 'Outros', 'Logística', 'Hospital', nan,
       'Hotel', 'Renda'], dtype=object)

In [10]:
df_fiis.columns

Index(['Código do fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'Dividend Yield', 'DY (3M) Acumulado', 'DY (6M) Acumulado',
       'DY (12M) Acumulado', 'DY (3M) Média', 'DY (6M) Média',
       'DY (12M) Média', 'DY Ano', 'Variação Preço', 'Rentab. Período',
       'Rentab. Acumulada', 'Patrimônio Líq.', 'VPA', 'P/VPA',
       'DY Patrimonial', 'Variação Patrimonial', 'Rentab. Patr. no Período',
       'Rentab. Patr. Acumulada', 'Vacância Física', 'Vacância Financeira',
       'Quantidade Ativos'],
      dtype='object')

In [11]:
df_fiis.isna().sum()

Código do fundo               0
Setor                        16
Preço Atual                   1
Liquidez Diária               1
Dividendo                     0
Dividend Yield                6
DY (3M) Acumulado             6
DY (6M) Acumulado             6
DY (12M) Acumulado            6
DY (3M) Média                 6
DY (6M) Média                 6
DY (12M) Média                6
DY Ano                       44
Variação Preço                6
Rentab. Período               6
Rentab. Acumulada             6
Patrimônio Líq.               9
VPA                           9
P/VPA                        10
DY Patrimonial               98
Variação Patrimonial         98
Rentab. Patr. no Período     98
Rentab. Patr. Acumulada      98
Vacância Física             250
Vacância Financeira         350
Quantidade Ativos             0
dtype: int64

In [12]:
categorical_columns = ['Código do fundo','Setor']
idx = df_fiis[df_fiis['Setor'].isna()].index
df_fiis.drop(idx, inplace=True)
df_fiis[categorical_columns].isna().sum()

Código do fundo    0
Setor              0
dtype: int64

In [13]:
df_fiis[categorical_columns] = df_fiis[categorical_columns].astype('category')
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 379
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Código do fundo           364 non-null    category
 1   Setor                     364 non-null    category
 2   Preço Atual               363 non-null    object
 3   Liquidez Diária           363 non-null    float64
 4   Dividendo                 364 non-null    object
 5   Dividend Yield            358 non-null    object
 6   DY (3M) Acumulado         358 non-null    object
 7   DY (6M) Acumulado         358 non-null    object
 8   DY (12M) Acumulado        358 non-null    object
 9   DY (3M) Média             358 non-null    object
 10  DY (6M) Média             358 non-null    object
 11  DY (12M) Média            358 non-null    object
 12  DY Ano                    320 non-null    object
 13  Variação Preço            358 non-null    object
 14  Rentab. Período           358 non-null    object
 15  Rentab. Acumulada         358 non-null    object
 16  Patrimônio Líq.           364 non-null    object
 17  VPA                       364 non-null    object
 18  P/VPA                     363 non-null    float64
 19  DY Patrimonial            275 non-null    object
 20  Variação Patrimonial      275 non-null    object
 21  Rentab. Patr. no Período  275 non-null    object
 22  Rentab. Patr. Acumulada   275 non-null    object
 23  Vacância Física           130 non-null    object
 24  Vacância Financeira       30 non-null     object
 25  Quantidade Ativos         364 non-null    int64
dtypes: category(2), float64(2), int64(1), object(21)
memory usage: 82.8+ KB

In [14]:
df_fiis.isna().sum()

Código do fundo               0
Setor                         0
Preço Atual                   1
Liquidez Diária               1
Dividendo                     0
Dividend Yield                6
DY (3M) Acumulado             6
DY (6M) Acumulado             6
DY (12M) Acumulado            6
DY (3M) Média                 6
DY (6M) Média                 6
DY (12M) Média                6
DY Ano                       44
Variação Preço                6
Rentab. Período               6
Rentab. Acumulada             6
Patrimônio Líq.               0
VPA                           0
P/VPA                         1
DY Patrimonial               89
Variação Patrimonial         89
Rentab. Patr. no Período     89
Rentab. Patr. Acumulada      89
Vacância Física             234
Vacância Financeira         334
Quantidade Ativos             0
dtype: int64

In [15]:
col_floats = list(df_fiis.iloc[:,2:-1].columns)
df_fiis[col_floats] = df_fiis[col_floats].fillna(value=0)
df_fiis[col_floats]

,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,DY (3M) Média,DY (6M) Média,DY (12M) Média,...,Rentab. Acumulada,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira
0,"R$ 3,32",826.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"0,00%","R$ 65.352.435,22","R$ 6,94",48.0,0,0,0,0,"56,00%",0
1,"R$ 17,01",2.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"1,14%","R$ 433.127.158,26","R$ 10,49",162.0,0,0,0,0,0,0
2,"R$ 8,82",2223.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-37,83%","R$ 27.688.895,17","R$ 13,26",67.0,0,0,0,0,"0,00%","100,00%"
3,"R$ 885,00",32.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-28,29%","R$ 250.446.109,75","R$ 2.252,68",39.0,0,0,0,0,"64,05%",0
4,"R$ 21,68",380.0,"R$ 0,00","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%","0,00%",...,"-31,62%","R$ -12.026.292,32","R$ -15,86",-137.0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,"R$ 62,48",94.0,"R$ 0,30","0,48%","1,37%","2,32%","0,00%","0,46%","0,39%","0,00%",...,"-5,15%","R$ 531.797.948,23","R$ 123,53",51.0,0,0,0,0,"5,80%",0
376,"R$ 94,24",46428.0,"R$ 0,77","0,82%","2,29%","4,41%","8,71%","0,76%","0,74%","0,73%",...,"8,78%","R$ 2.058.454.896,67","R$ 101,30",93.0,0,0,0,0,"3,90%",0
377,"R$ 111,00",4224.0,"R$ 0,76","0,69%","1,97%","4,20%","8,51%","0,66%","0,70%","0,71%",...,"4,48%","R$ 364.091.433,44","R$ 104,80",106.0,0,0,0,0,"0,00%",0
378,"R$ 70,92",6374.0,"R$ 0,65","0,92%","2,51%","4,97%","9,41%","0,84%","0,83%","0,78%",...,"-9,72%","R$ 742.296.242,19","R$ 103,81",68.0,0,0,0,0,"17,30%","12,00%"
379,"R$ 9,69",3784.0,"R$ 0,11","1,14%","3,43%","17,04%","0,00%","1,14%","2,84%","0,00%",...,"-87,69%","R$ 49.267.646,34","R$ 9,80",99.0,0,0,0,0,0,0

In [16]:
df_fiis[col_floats] = df_fiis[col_floats].applymap(lambda x: str(x).replace('R$', '').replace('.0','').replace('.','').replace('%','').replace(',','.'))
df_fiis[col_floats] = df_fiis[col_floats].astype('float')
df_fiis['Liquidez Diária'] = df_fiis['Liquidez Diária'].astype('int64')
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 379
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Código do fundo           364 non-null    category
 1   Setor                     364 non-null    category
 2   Preço Atual               364 non-null    float64
 3   Liquidez Diária           364 non-null    int64
 4   Dividendo                 364 non-null    float64
 5   Dividend Yield            364 non-null    float64
 6   DY (3M) Acumulado         364 non-null    float64
 7   DY (6M) Acumulado         364 non-null    float64
 8   DY (12M) Acumulado        364 non-null    float64
 9   DY (3M) Média             364 non-null    float64
 10  DY (6M) Média             364 non-null    float64
 11  DY (12M) Média            364 non-null    float64
 12  DY Ano                    364 non-null    float64
 13  Variação Preço            364 non-null    float64
 14  Rentab. Período           364 non-null    float64
 15  Rentab. Acumulada         364 non-null    float64
 16  Patrimônio Líq.           364 non-null    float64
 17  VPA                       364 non-null    float64
 18  P/VPA                     364 non-null    float64
 19  DY Patrimonial            364 non-null    float64
 20  Variação Patrimonial      364 non-null    float64
 21  Rentab. Patr. no Período  364 non-null    float64
 22  Rentab. Patr. Acumulada   364 non-null    float64
 23  Vacância Física           364 non-null    float64
 24  Vacância Financeira       364 non-null    float64
 25  Quantidade Ativos         364 non-null    int64
dtypes: category(2), float64(22), int64(2)
memory usage: 82.8 KB

In [17]:
df_fiis.describe()

,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,DY (3M) Média,DY (6M) Média,DY (12M) Média,...,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira,Quantidade Ativos
count,364.000000,3.640000e+02,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,...,3.640000e+02,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000,364.000000
mean,106.331511,2.691933e+04,21.597335,1.154231,2.478681,4.567115,7.661978,0.826126,0.761374,0.638764,...,3.847102e+08,3218.161951,73.282967,0.662418,-0.658379,-0.030907,2.331511,5.296236,0.919533,2.431319
std,200.086892,1.748407e+05,116.263654,2.679201,2.775132,3.429836,5.508020,0.925188,0.571418,0.459148,...,7.469296e+08,13883.019601,57.524503,1.960335,4.842638,4.603129,14.990449,14.929223,6.619988,6.911739
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.226292e+06,-15.860000,-137.000000,0.000000,-40.990000,-40.750000,-98.840000,0.000000,0.000000,0.000000
25%,61.822500,4.005000e+02,0.440000,0.560000,1.537500,1.930000,0.460000,0.510000,0.320000,0.040000,...,6.483144e+07,88.880000,59.000000,0.105000,-0.740000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,84.405000,2.612000e+03,0.700000,0.860000,2.365000,4.940000,9.065000,0.790000,0.825000,0.760000,...,1.443088e+08,99.140000,81.000000,0.615000,0.000000,0.070000,2.930000,0.000000,0.000000,0.000000
75%,95.990000,1.183575e+04,1.005000,1.040000,2.905000,6.137500,11.970000,0.970000,1.022500,1.000000,...,3.579716e+08,117.985000,93.000000,0.830000,0.000000,0.660000,7.940000,0.000000,0.000000,1.000000
max,2000.000000,3.180000e+06,783.960000,18.780000,18.780000,18.780000,18.850000,6.260000,3.130000,1.570000,...,7.645647e+09,67453.050000,949.000000,36.830000,57.540000,58.430000,37.550000,100.000000,100.000000,72.000000

In [18]:
df_fiis['Vacância Física'] = df_fiis['Vacância Física']/100
df_fiis['Vacância Financeira'] = df_fiis['Vacância Financeira']/100
df_fiis['P/VPA'] = df_fiis['P/VPA']/100

tipo = []
for row in df_fiis['Setor']:
    if row in ('Shoppings','Lajes Corporativas','Residencial','Logística','Hospital','Hotel'):
        tipo.append('Tijolo')
    else: tipo.append('Papel')

df_fiis.insert(1,'Tipo',tipo)

df_fiis.head()

,Código do fundo,Tipo,Setor,Preço Atual,Liquidez Diária,Dividendo,Dividend Yield,DY (3M) Acumulado,DY (6M) Acumulado,DY (12M) Acumulado,...,Patrimônio Líq.,VPA,P/VPA,DY Patrimonial,Variação Patrimonial,Rentab. Patr. no Período,Rentab. Patr. Acumulada,Vacância Física,Vacância Financeira,Quantidade Ativos
0,FIVN11,Tijolo,Shoppings,3.32,826,0.0,0.0,0.0,0.0,0.0,...,6.535244e+07,6.94,0.48,0.0,0.0,0.0,0.0,0.5600,0.0,1
1,BZLI11,Papel,Títulos e Val. Mob.,17.01,2,0.0,0.0,0.0,0.0,0.0,...,4.331272e+08,10.49,1.62,0.0,0.0,0.0,0.0,0.0000,0.0,0
2,XTED11,Tijolo,Lajes Corporativas,8.82,2223,0.0,0.0,0.0,0.0,0.0,...,2.768890e+07,13.26,0.67,0.0,0.0,0.0,0.0,0.0000,1.0,1
3,ALMI11,Tijolo,Lajes Corporativas,885.00,32,0.0,0.0,0.0,0.0,0.0,...,2.504461e+08,2252.68,0.39,0.0,0.0,0.0,0.0,0.6405,0.0,1
4,PABY11,Papel,Híbrido,21.68,380,0.0,0.0,0.0,0.0,0.0,...,-1.226292e+06,-15.86,-1.37,0.0,0.0,0.0,0.0,0.0000,0.0,1

In [19]:
df_fiis.to_csv("fiis.csv", index=False)